### ISSUE TITLE
Ripple is slightly offset to the right

### ISSUE THREAD

**Issue by plasmatech8** [plasmatech8/skeleton-material-theme#1]
See https://github.com/Posandu/svelte-ripple-action/issues/2#issuecomment-1737533264

![image](https://github.com/plasmatech8/skeleton-material-theme/assets/40431112/2bb60d2e-f652-4d13-9027-8c22164d7c1a)

Relating to `.btn`
```css
.btn>:not([hidden])~:not([hidden]) {
  --tw-space-x-reverse: 0;
  margin-right:calc(.5rem * var(--tw-space-x-reverse));
  margin-left:calc(.5rem * calc(1 - var(--tw-space-x-reverse)))
}
```
